# Generated by Django 3.1 on 2020-08-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('writer', models.CharField(max_length=50, verbose_name='작성자')),
                ('contents', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
